### ISSUE TITLE
API login retry logic not working

### ISSUE THREAD

**Issue by audiodude** [openzim/wikimedia_wp1_bot#69]
The retry logic that was added in https://github.com/openzim/wikimedia_wp1_bot/commit/d5769dd3c25888cd8a42c4ef3c8e4786c932bb2d is not working.

Here is the relevant snippet from the logs:
```
INFO:wp1.tables:Uploading wikicode to Wikipedia: Adele
WARNING:wp1.api:Got login exception, retrying login
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): en.wikipedia.org:443
DEBUG:urllib3.connectionpool:https://en.wikipedia.org:443 "GET /w/api.php?meta=siteinfo%7Cuserinfo%7Cuserinfo&siprop=general%7Cnamespaces&uiprop=groups%7Crights%7Cblockinfo%7Chasmsg&continue=&action=query&format=json HTTP/1.1" 200 2220
DEBUG:urllib3.connectionpool:https://en.wikipedia.org:443 "GET /w/api.php?meta=tokens&type=login&action=query&format=json HTTP/1.1" 200 110
DEBUG:urllib3.connectionpool:https://en.wikipedia.org:443 "POST /w/api.php HTTP/1.1" 200 88
DEBUG:urllib3.connectionpool:https://en.wikipedia.org:443 "GET /w/api.php?meta=userinfo%7Cuserinfo&uiprop=groups%7Crights%7Cblockinfo%7Chasmsg&continue=&action=query&format=json HTTP/1.1" 200 280
00:00:24 mwclient.errors.AssertUserFailedError: By default, mwclient protects you from accidentally editing without being logged in. If you actually want to edit without logging in, you can set force_login on the Site object to False.
Traceback (most recent call last):
  File "/usr/src/app/wp1/api.py", line 48, in save_page
    page.save(wikicode, msg)
  File "/usr/local/lib/python3.7/site-packages/mwclient/page.py", line 182, in save
    raise mwclient.errors.AssertUserFailedError()
mwclient.errors.AssertUserFailedError: By default, mwclient protects you from accidentally editing without being logged in. If you actually want to edit without logging in, you can set force_login on the Site object to False.
```

My current best guess, from looking at the mwclient code, is that the `page` object keeps a reference to the site it was pulled from, so that logging in again on the global site object perhaps doesn't do anything.

The other problem is that this is hard to test on Wikipedia, since the login time is presumably pretty long.

**Comment by audiodude** [comment]
This is, of course, why the bot didn't upload any tables today.

**Comment by audiodude** [comment]
I've restarted the upload worker and requeued the failed jobs. Some of them that failed were also update jobs, which seem to have some kind of stale database connection as well.

**Comment by audiodude** [comment]
The attempted fix (no-op token refresh) didn't work. Next step is to fork the mwclient repo and attempt a fix there.

**Comment by audiodude** [comment]
I tried replicating some of the code that I use in api.py in a simple script so I could inspect the results. Interestingly, I got the following when trying the second login attempt:

```
mwclient.errors.LoginError: Cannot log in when using MediaWiki\Session\BotPasswordSessionProvider sessions
```

I think the answer might just be to throw out the entire mwclient Site object when a retry is necessary.
